# Generated by Django 4.2 on 2023-05-04 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluguel', '0002_cliente_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='endereco',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Telefone'),
        ),
    ]
