# Generated by Django 4.2 on 2023-05-04 19:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aluguel', '0003_alter_cliente_data_nascimento_alter_cliente_endereco_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluguel',
            name='cpf',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cliente_alugueis', to='aluguel.cliente'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(blank=True, max_length=15, primary_key=True, serialize=False, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
