# Generated by Django 4.2 on 2023-05-04 19:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aluguel', '0004_alter_aluguel_cpf_alter_cliente_cpf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluguel',
            name='cpf',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cliente_alugueis', to='aluguel.cliente'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aluguel',
            name='placa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='aluguel.carro', verbose_name='Carro'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='user',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
